; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.36"

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[sajatblog][download][type] = "git"
projects[sajatblog][download][url] = "git@github.com:tanarurkerem/sajatblog.git"
projects[sajatblog][type] = "profile"

projects[features][version] = "2.4"

projects[tanarurkerem_ckeditor][download][type] = "git"
projects[tanarurkerem_ckeditor][download][url] = "git@github.com:tanarurkerem/tanarurkerem_ckeditor.git"
projects[tanarurkerem_ckeditor][type] = "module"




